#if !canImport(ObjectiveC)
import XCTest

extension PlaceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlaceTests = [
        ("testPlacesCannotBeRetrievedWithInvalidLangParam", testPlacesCannotBeRetrievedWithInvalidLangParam),
        ("testPlacesCannotBeRetrievedWithInvalidStatusParam", testPlacesCannotBeRetrievedWithInvalidStatusParam),
        ("testPlacesCannotBeRetrievedWithoutApiKey", testPlacesCannotBeRetrievedWithoutApiKey),
        ("testPlacesCannotBeRetrievedWithoutLangParam", testPlacesCannotBeRetrievedWithoutLangParam),
        ("testPlacesCannotBeRetrievedWitInvalidApiKey", testPlacesCannotBeRetrievedWitInvalidApiKey),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PlaceTests.__allTests__PlaceTests),
    ]
}
#endif
