#if !canImport(ObjectiveC)
import XCTest

extension PlaceDataVersionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlaceDataVersionTests = [
        ("testPlaceDataVersionCanBeRetrievedAndInPast", testPlaceDataVersionCanBeRetrievedAndInPast),
        ("testPlaceDataVersionCannotBeRetrievedWithoutApiKey", testPlaceDataVersionCannotBeRetrievedWithoutApiKey),
        ("testPlaceDataVersionCannotBeRetrievedWitInvalidApiKey", testPlaceDataVersionCannotBeRetrievedWitInvalidApiKey),
    ]
}

extension PlaceReportTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlaceReportTests = [
        ("testPlaceReportCanBeSavedAndRetrived", testPlaceReportCanBeSavedAndRetrived),
        ("testPlaceReportCannotBeSavedWithInvalidFields", testPlaceReportCannotBeSavedWithInvalidFields),
        ("testPlaceReportsCanBeRetrieved", testPlaceReportsCanBeRetrieved),
        ("testPlaceReportsCanBeRetrievedWithActiveStatus", testPlaceReportsCanBeRetrievedWithActiveStatus),
        ("testPlaceReportsCanBeRetrievedWithDeletedStatus", testPlaceReportsCanBeRetrievedWithDeletedStatus),
        ("testPlaceReportsCannotBeRetrievedWithInvalidStatusParam", testPlaceReportsCannotBeRetrievedWithInvalidStatusParam),
        ("testPlaceReportsCannotBeRetrievedWithoutApiKey", testPlaceReportsCannotBeRetrievedWithoutApiKey),
        ("testPlaceReportsCannotBeRetrievedWitInvalidApiKey", testPlaceReportsCannotBeRetrievedWitInvalidApiKey),
    ]
}

extension PlaceSuggestionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlaceSuggestionTests = [
        ("testPlaceSuggestionCanBeSavedAndRetrived", testPlaceSuggestionCanBeSavedAndRetrived),
        ("testPlaceSuggestionCannotBeSavedWithInvalidFields", testPlaceSuggestionCannotBeSavedWithInvalidFields),
        ("testPlaceSuggestionsCanBeRetrieved", testPlaceSuggestionsCanBeRetrieved),
        ("testPlaceSuggestionsCanBeRetrievedWithActiveStatus", testPlaceSuggestionsCanBeRetrievedWithActiveStatus),
        ("testPlaceSuggestionsCanBeRetrievedWithDeletedStatus", testPlaceSuggestionsCanBeRetrievedWithDeletedStatus),
        ("testPlaceSuggestionsCannotBeRetrievedWithInvalidStatusParam", testPlaceSuggestionsCannotBeRetrievedWithInvalidStatusParam),
        ("testPlaceSuggestionsCannotBeRetrievedWithoutApiKey", testPlaceSuggestionsCannotBeRetrievedWithoutApiKey),
        ("testPlaceSuggestionsCannotBeRetrievedWitInvalidApiKey", testPlaceSuggestionsCannotBeRetrievedWitInvalidApiKey),
    ]
}

extension PlaceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PlaceTests = [
        ("testPlacesCanBeRetrievedWithENLanguageAndDeletedStatus", testPlacesCanBeRetrievedWithENLanguageAndDeletedStatus),
        ("testPlacesCanBeRetrievedWithHULanguageAndActiveStatus", testPlacesCanBeRetrievedWithHULanguageAndActiveStatus),
        ("testPlacesCanBeRetrievedWithHULanguage", testPlacesCanBeRetrievedWithHULanguage),
        ("testPlacesCannotBeRetrievedWithInvalidLangParam", testPlacesCannotBeRetrievedWithInvalidLangParam),
        ("testPlacesCannotBeRetrievedWithInvalidStatusParam", testPlacesCannotBeRetrievedWithInvalidStatusParam),
        ("testPlacesCannotBeRetrievedWithoutApiKey", testPlacesCannotBeRetrievedWithoutApiKey),
        ("testPlacesCannotBeRetrievedWithoutLangParam", testPlacesCannotBeRetrievedWithoutLangParam),
        ("testPlacesCannotBeRetrievedWitInvalidApiKey", testPlacesCannotBeRetrievedWitInvalidApiKey),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PlaceDataVersionTests.__allTests__PlaceDataVersionTests),
        testCase(PlaceReportTests.__allTests__PlaceReportTests),
        testCase(PlaceSuggestionTests.__allTests__PlaceSuggestionTests),
        testCase(PlaceTests.__allTests__PlaceTests),
    ]
}
#endif
